// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCRl0QVrJ0BE4Rw_zfJyKbeEblHRdhys',
    appId: '1:453658963632:web:46223981db9c03eafdd575',
    messagingSenderId: '453658963632',
    projectId: 'spotify-clone-2036-6cea8',
    authDomain: 'spotify-clone-2036-6cea8.firebaseapp.com',
    storageBucket: 'spotify-clone-2036-6cea8.firebasestorage.app',
    measurementId: 'G-5D6SNYZV9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBobe7zlF3a8cw4V2-qiT1nF3c9uAeluRs',
    appId: '1:453658963632:android:cd2fa3d80e1f93fafdd575',
    messagingSenderId: '453658963632',
    projectId: 'spotify-clone-2036-6cea8',
    storageBucket: 'spotify-clone-2036-6cea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-Yjl9vSr4JV25eHbWBrqhYBQST8MZQw',
    appId: '1:453658963632:ios:0ea5c448959fca90fdd575',
    messagingSenderId: '453658963632',
    projectId: 'spotify-clone-2036-6cea8',
    storageBucket: 'spotify-clone-2036-6cea8.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-Yjl9vSr4JV25eHbWBrqhYBQST8MZQw',
    appId: '1:453658963632:ios:0ea5c448959fca90fdd575',
    messagingSenderId: '453658963632',
    projectId: 'spotify-clone-2036-6cea8',
    storageBucket: 'spotify-clone-2036-6cea8.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDCRl0QVrJ0BE4Rw_zfJyKbeEblHRdhys',
    appId: '1:453658963632:web:f6bbaf37d20f04e6fdd575',
    messagingSenderId: '453658963632',
    projectId: 'spotify-clone-2036-6cea8',
    authDomain: 'spotify-clone-2036-6cea8.firebaseapp.com',
    storageBucket: 'spotify-clone-2036-6cea8.firebasestorage.app',
    measurementId: 'G-T6BF774FRD',
  );
}
